ALTER TABLE `Collection` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `Environment` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `Request` ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0;
